(cl:defpackage ros_impedance_controller-srv
  (:use )
  (:export
   "GENERIC_FLOAT"
   "<GENERIC_FLOAT-REQUEST>"
   "GENERIC_FLOAT-REQUEST"
   "<GENERIC_FLOAT-RESPONSE>"
   "GENERIC_FLOAT-RESPONSE"
   "GET_EFFORT_PID"
   "<GET_EFFORT_PID-REQUEST>"
   "GET_EFFORT_PID-REQUEST"
   "<GET_EFFORT_PID-RESPONSE>"
   "GET_EFFORT_PID-RESPONSE"
   "GET_MAP"
   "<GET_MAP-REQUEST>"
   "GET_MAP-REQUEST"
   "<GET_MAP-RESPONSE>"
   "GET_MAP-RESPONSE"
   "SET_PIDS"
   "<SET_PIDS-REQUEST>"
   "SET_PIDS-REQUEST"
   "<SET_PIDS-RESPONSE>"
   "SET_PIDS-RESPONSE"
  ))

