<?xml version="1.0" ?>
<robot name="climbingrobot2landing" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- This file is based on: https://atlas.is.localnet/confluence/display/AMDW/Quadruped+URDF+Files -->

    <!--- new_gazebo_version should be false by default because pinocchio needs it!-->
    <xacro:arg name="robot_name" default="climbingrobot2landing"/> 
    <xacro:arg name="new_gazebo_version" default="false"/>

   <xacro:arg name="anchorX" default="0."/>	
   <xacro:arg name="anchorY" default="0."/>	
   <xacro:arg name="anchorZ" default="20."/>	

   <xacro:arg name="anchor2X" default="0."/>	
   <xacro:arg name="anchor2Y" default="5."/>	
   <xacro:arg name="anchor2Z" default="20."/>	

   <xacro:arg name="hoist_distance" default="0.1"/>	
   <xacro:arg name="hoist_base_distanceZ" default="0.05"/>
   <xacro:arg name="lowerleg_landing_length" default="0.3"/>

    <xacro:property name="WHEEL_pos" value="0.10183" />

    <xacro:include filename="$(find climbingrobot_description)/gazebo/gazebo.urdf.xacro">
        <xacro:arg name="task_period" value="$(arg task_period)"/>
	<xacro:arg name="robot_name" value="$(arg robot_name)"/>
    </xacro:include>


    <xacro:include filename="$(find climbingrobot_description)/urdf/climbingrobot2landing.transmission.xacro"/>

 <material name="Blue">
    <color rgba="${0/255} ${0/255} ${255/255} 1.0"/>
  </material>


<!--this is just to plot the target in gazebo as a ball

    <joint name="target_link" type="fixed">
        <origin rpy="0 0 0" xyz=" 3.   3. 0."/>
        <parent link="world"/>
        <child link="target"/>
    </joint>-->
<!--
    <link name="target">
    <visual>
	<geometry>
         <sphere radius="0.4" />
	</geometry>
    </visual>-->
  <!--<inertial>
      <origin rpy="0 0 0" xyz="0 0 0.0"/>
      <mass value="0.01"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>-->

    <link name="world"/>


 <!-- Anchor 1 link-->

   <joint name="anchor1_position" type="fixed">
        <origin rpy="0 0 0" xyz="$(arg anchorX) $(arg anchorY) $(arg anchorZ)"/>
        <parent link="world"/>
        <child link="anchor"/>
    </joint>

    <link name="anchor">
    <visual>
	<geometry>
         <sphere radius="0.4" />
	</geometry>
    </visual>
     
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0.0"/>
      <mass value="0.01"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>



  <!-- Revolute pitch joint between the anchor1 and the wire -->
  <joint name="mountain_wire_pitch_l" type="revolute">
    <parent link="anchor"/>
    <child link="pre_wire1"/>
    <limit effort="1000" velocity="100.0" lower="-100" upper="100"/>
    <!-- joint rotates about -y axis -->
    <axis xyz="0 -1 0"/>
    <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
    <!-- pybullet simulation parameters -->
    <dynamics damping="0.0" friction="0.0"/>
  </joint>


  <link name="pre_wire1">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://climbingrobot_description/meshes/obj/cylinder.obj" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="grey">
        <color rgba=".7 .7 .7 .5"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0.0"/>
      <geometry>
        <cylinder length="0.01" radius="0.01"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0.0"/>
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>

  <!-- Revolute roll joint between the mountain and the wire -->
  <joint name="mountain_wire_roll_l" type="revolute">
    <parent link="pre_wire1"/>
    <child link="wire"/>
    <limit effort="1000" velocity="100.0" lower="-100" upper="100"/>
    <!-- joint rotates about x axis -->
    <axis xyz="1 0 0"/>
    <origin rpy="1.57 0 0" xyz="0.0 0.0 0.0"/>
    <!-- pybullet simulation parameters -->
    <dynamics damping="0.0" friction="0.0"/>
  </joint>




  <link name="wire">    
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0.0"/>
      <mass value="0.01"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>

  <!-- Prismatic joint between the wire and the base -->
  <joint name="wire_base_prismatic_l" type="prismatic">
    <parent link="wire"/>
    <child link="pre-base1"/>
    <limit effort="1000" velocity="100.0" lower="-100" upper="100"/>
    <!-- joint translates on z axis -->
    <axis xyz="0 0 -1"/>
    <origin rpy="0 0 0" xyz="0.0 0.0 ${$(arg hoist_distance)/2 -$(arg anchor2Y)/2}"/>
    <!-- pybullet simulation parameters -->
    <dynamics damping="0.0" friction="0.0"/>
  </joint>



  <link name="pre-base1"> 
      <visual>
      <origin rpy="0 0 0" xyz="0 0 ${$(arg anchorZ)/2}"/>
     <geometry>
           <cylinder radius="0.05" length="$(arg anchorZ)"/>
      </geometry>
 	      <material name="grey">
 	        <color rgba=".7 .7 .7 .5"/>
 	      </material>
     </visual>  	
     <!--collision>
 	      <origin rpy="0 0 0" xyz="0 0 $(arg anchorZ)"/>
 	      <geometry>
 	        <cylinder radius="0.05" length="${$(arg anchorZ)*2}"/>
 	      </geometry>
 	      <material name="grey">
 	        <color rgba=".7 .7 .7 .5"/>
 	      </material>
    </collision--> 
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0.0"/>
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>

  <!-- Revolute pitch joint between the wire and the base -->
  <joint name="wire_base_pitch_l" type="revolute">
    <parent link="pre-base1"/>
    <child link="pre-base2"/>
    <limit effort="1000" velocity="100.0" lower="-100" upper="100"/>
    <!-- joint rotates about y axis -->
    <axis xyz="0 1 0"/>
    <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
    <!-- pybullet simulation parameters -->
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <link name="pre-base2">
     <inertial>
      <origin rpy="0 0 0" xyz="0 0 0.0"/>
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>
  <!-- Revolute roll joint between the wire and the base -->
  <joint name="wire_base_roll_l" type="revolute">
    <parent link="pre-base2"/>
    <child link="pre-base3"/>
    <limit effort="1000" velocity="100.0" lower="-100" upper="100"/>
    <!-- joint rotates about x axis -->
    <axis xyz="1 0 0"/>
    <origin rpy="-1.57 0 0" xyz="0.0 0.0 0.0"/>
    <!-- pybullet simulation parameters -->
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <link name="pre-base3">   
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0.0"/>
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>
  <!-- Revolute yaw joint between the wire and the base -->
  <joint name="wire_base_yaw_l" type="revolute">
    <parent link="pre-base3"/>
    <child link="base_link"/>
    <limit effort="1000" velocity="100.0" lower="-100" upper="100"/>
    <!-- joint rotates about z axis -->
    <axis xyz="0 0 1"/>
    <origin rpy="0 0 0" xyz="0.0 ${$(arg hoist_distance)/2} -$(arg hoist_base_distanceZ)"/>
    <!-- pybullet simulation parameters -->
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

 

  <!-- Anchor 2   -->


   <joint name="anchor2_position" type="fixed">
        <origin rpy="0 0 0" xyz="0 $(arg anchor2Y) 0"/>
        <parent link="anchor"/>
        <child link="anchor_2"/>
    </joint>
	

    <link name="anchor_2">
	    <visual>
		<geometry>
		 <sphere radius="0.4" />
		</geometry>
		<material name="Blue"/><!--rviz"/-->
	    </visual>
	     
	    <inertial>
	      <origin rpy="0 0 0" xyz="0 0 0.0"/>
	      <mass value="0.01"/>
	      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
	    </inertial>
    </link>



  <!-- Revolute pitch joint between the mountain and the wire -->
  <joint name="mountain_wire_pitch_r" type="revolute">
    <parent link="anchor_2"/>
    <child link="pre_wire1_2"/>
    <limit effort="1000" velocity="100.0" lower="-100" upper="100"/>
    <!-- joint rotates about -y axis -->
    <axis xyz="0 -1 0"/>
    <origin rpy="-${pi/2}  0 0" xyz="0.0 0.0 0.0"/>
    <!-- pybullet simulation parameters -->
    <dynamics damping="0.0" friction="0.0"/>
  </joint>


  <link name="pre_wire1_2">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://climbingrobot_description/meshes/obj/cylinder.obj" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="grey">
        <color rgba=".7 .7 .7 .5"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0.0"/>
      <geometry>
        <cylinder length="0.01" radius="0.01"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0.0"/>
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>

  <!-- Revolute roll joint between the mountain and the wire -->
  <joint name="mountain_wire_roll_r" type="revolute">
    <parent link="pre_wire1_2"/>
    <child link="wire_2"/>
    <limit effort="1000" velocity="100.0" lower="-100" upper="100"/>
    <!-- joint rotates about x axis -->
    <axis xyz="1 0 0"/>
    <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
    <!-- pybullet simulation parameters -->
    <dynamics damping="0.0" friction="0.0"/>
  </joint>


  <link name="wire_2">    
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0.0"/>
      <mass value="0.01"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>

  <!-- Prismatic joint between the wire and the base -->
  <joint name="wire_base_prismatic_r" type="prismatic">
    <parent link="wire_2"/>
    <child link="pre-base1_2"/>
    <limit effort="1000" velocity="100.0" lower="-100" upper="100"/>
    <!-- joint translates on x axis -->
    <axis xyz="0 0 -1"/>
    <origin rpy="0 0 0" xyz="0.0 0.0  ${$(arg hoist_distance)/2 -$(arg anchor2Y)/2}"/>
    <!-- pybullet simulation parameters -->
    <dynamics damping="0.0" friction="0.0"/>
  </joint>



  <link name="pre-base1_2"> 
      <visual>
       	      <origin rpy="0 0 0" xyz="0 0 $(arg anchorZ)"/>
 	      <geometry>
 	        <cylinder radius="0.05" length="${$(arg anchorZ)*2}"/>
 	      </geometry>
 	      <material name="grey">
 	        <color rgba=".7 .7 .7 .5"/>
 	      </material>
     </visual>  	
     <!--collision>
 	      <origin rpy="0 0 0" xyz="0 0 ${$(arg anchorZ)/2}"/>
 	      <geometry>
 	        <cylinder radius="0.05" length="$(arg anchorZ)"/>
 	      </geometry>
 	      <material name="grey">
 	        <color rgba=".7 .7 .7 .5"/>
 	      </material>
    </collision--> 
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0.0"/>
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>

  <!-- Revolute pitch joint between the wire and the base -->
  <joint name="wire_base_pitch_r" type="revolute">
    <parent link="pre-base1_2"/>
    <child link="pre-base2_2"/>
    <limit effort="1000" velocity="100.0" lower="-100" upper="100"/>
    <!-- joint rotates about y axis -->
    <axis xyz="0 1 0"/>
    <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
    <!-- pybullet simulation parameters -->
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <link name="pre-base2_2">
     <inertial>
      <origin rpy="0 0 0" xyz="0 0 0.0"/>
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>
  <!-- Revolute roll joint between the wire and the base -->
  <joint name="wire_base_roll_r" type="revolute">
    <parent link="pre-base2_2"/>
    <child link="pre-base3_2"/>
    <limit effort="1000" velocity="100.0" lower="-100" upper="100"/>
    <!-- joint rotates about x axis -->
    <axis xyz="1 0 0"/>
    <origin rpy="1.57 0 0" xyz="0.0 0.0 0.0"/>
    <!-- pybullet simulation parameters -->
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <link name="pre-base3_2">   
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0.0"/>
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>


  <joint name="wire_base_yaw_r" type="revolute">
    <parent link="pre-base3_2"/>
    <child link="fake_link"/>
    <limit effort="1000" velocity="100.0" lower="-100" upper="100"/>
    <!-- joint rotates about x axis -->
    <axis xyz="0 0 1"/>
    <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
    <!-- pybullet simulation parameters -->
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <link name="fake_link">   
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0.0"/>
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>


 <!-- closing the loop for gazebo not used by pinocchio -->
 <gazebo>  
	  <joint name="fixed_joint" type="fixed">
		 <pose>0 ${$(arg hoist_distance)/2} $(arg hoist_base_distanceZ) 0 0 0 0</pose>
		 <parent>fake_link</parent>
		 <child>base_link</child>		
	  </joint>  
 </gazebo>


  <link name="base_link">
    <!-- BASE LINK INERTIAL -->
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 -0.05"/>
      <!-- <mass value="0.36"/> -->
      <mass value="13.47"/>
      <!-- The base is extremely symmetrical. -->
      <inertia ixx="0.5" ixy="0.0" ixz="0.0" iyy="0.5" iyz="0.0" izz="0.5"/>
    </inertial>
    <!-- BASE LINK VISUAL -->
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://climbingrobot_description/meshes/obj/with_foot/solo_body.obj" scale="1 1 1"/>
      </geometry>
      <material name="red">
        <color rgba="0.749 0.380 0.410 1.0"/>
      </material>
    </visual>
    <!-- BASE LINK COLLISION -->
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://climbingrobot_description/meshes/obj/with_foot/solo_body.obj" scale="1 1 1"/>
      </geometry>
    </collision>
    <!-- Bullet specific paramters -->
    <contact>
      <lateral_friction value="1.0"/>
      <restitution value="0.5"/>
    </contact>
  </link>
  <!-- END BASE LINK -->


<!--LANDING MECHANISM LEFT-->

  <joint name="hip_yaw_landing_l" type="revolute">
    <parent link="base_link"/>
    <child link="lowerleg_landing_l"/>
    <limit effort="1000" velocity="100.0" lower="-100" upper="100"/>
    <!-- joints rotates around the z-axis -->
    <axis xyz="0 0 1"/>
    <origin rpy="0 0 1.57" xyz="0.0 -0.08 0.025"/>
    <!-- pybullet simulation parameters -->
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <link name="lowerleg_landing_l">
    <!-- Left upper leg inertia -->
    <inertial>
      <origin rpy="0 0 0" xyz="0.0000 0.0 -0.0"/>
      <mass value="0.01"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.00004671" izz="0.01"/>
    </inertial>
    <visual>
      <origin rpy="0 -1.57 0" xyz="-${$(arg lowerleg_landing_length)/2} 0 0"/>
      <geometry>
           <cylinder radius="0.02" length="$(arg lowerleg_landing_length)"/>
      </geometry> 
     <material name="grey">
        <color rgba="0.8 0.8 0.8 1.0"/>
      </material>
    </visual>
  </link>

  <joint name="ankle_landing_l" type="fixed">
    <parent link="lowerleg_landing_l"/>
    <child link="foot_landing_l"/>
    <origin rpy="0 0 0" xyz="-$(arg lowerleg_landing_length) 0. 0"/>
    <!-- Limits (usefull?) -->
    <limit effort="1000" lower="-10" upper="10" velocity="1000"/>
    <!-- pybullet simulation parameters -->
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <link name="foot_landing_l">
    <!-- FOOT INERTIAL -->
    <!-- This link is symmetrical left or right -->
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0.00035767"/>
      <mass value="0.00693606"/>
      <inertia ixx="0.00000057" ixy="0.0" ixz="0.0" iyy="0.00000084" iyz="0.0" izz="0.00000053"/>
    </inertial>
    <!-- FOOT VISUAL -->
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.02175" />
      </geometry>
	<material name="black">
		<color rgba="0.263 0.298 0.369 1"/>
	</material>
    </visual>
    <!-- FOOT COLLISION -->
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.02175" />
      </geometry>
      <material name="grey">
        <color rgba="0.7 0.7 0.7 0.5"/>
      </material>
    </collision>
   </link>

 <gazebo reference="wheel_l">
        <kp>1000000.0</kp>
        <kd>100.0</kd>
        <mu1>1.8</mu1>
        <mu2>1.8</mu2>
        <maxVel>1.0</maxVel>
        <maxContacts>1</maxContacts>
        <sensor name="foot_contact_sensor" type="contact">
                <always_on>true</always_on>
                <update_rate>1000.0</update_rate>
                <contact>
                <collision>wheel_l_collision</collision>
                </contact>
                <!-- the sensor readings in terms of force torques are expressed in the lowerleg frame
                because gazebo lumps the fake footframe with the real parent link, the normals are in the world frame-->
                <plugin name="foot_bumper" filename="libgazebo_ros_bumper.so">
                        <bumperTopicName>/$(arg robot_name)/foot_landing_l_bumper</bumperTopicName>
                        <!--robotNamespace>solo</robotNamespace-->
                        <frameName>wheel_l</frameName>
                </plugin>
        </sensor>
        <material>Gazebo/Black</material>
   </gazebo>

<!--LANDING MECHANISM RIGHT-->

  <joint name="hip_yaw_landing_r" type="revolute">
    <parent link="base_link"/>
    <child link="lowerleg_landing_r"/>
    <limit effort="1000" velocity="100.0" lower="-100" upper="100"/>
    <!-- joints rotates around the z-axis -->
    <axis xyz="0 0 1"/>
    <origin rpy="0 0 -1.57" xyz="0.0 0.08 0.025"/>
    <!-- pybullet simulation parameters -->
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <link name="lowerleg_landing_r">
    <!-- Left upper leg inertia -->
    <inertial>
      <origin rpy="0 0 0" xyz="0.0000 0.0 -0.0"/>
      <mass value="0.01"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.00004671" izz="0.01"/>
    </inertial>
    <visual>
      <origin rpy="0 -1.57 0" xyz="-${$(arg lowerleg_landing_length)/2} 0 0"/>
      <geometry>
           <cylinder radius="0.02" length="$(arg lowerleg_landing_length)"/>
      </geometry> 
     <material name="grey">
        <color rgba="0.8 0.8 0.8 1.0"/>
      </material>
    </visual>
  </link>

  <joint name="ankle_landing_r" type="fixed">
    <parent link="lowerleg_landing_r"/>
    <child link="foot_landing_r"/>
    <origin rpy="0 0 0" xyz="-$(arg lowerleg_landing_length) 0. 0"/>
    <!-- Limits (usefull?) -->
    <limit effort="1000" lower="-10" upper="10" velocity="1000"/>
    <!-- pybullet simulation parameters -->
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <link name="foot_landing_r">
    <!-- FOOT INERTIAL -->
    <!-- This link is symmetrical left or right -->
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0.00035767"/>
      <mass value="0.00693606"/>
      <inertia ixx="0.00000057" ixy="0.0" ixz="0.0" iyy="0.00000084" iyz="0.0" izz="0.00000053"/>
    </inertial>
    <!-- FOOT VISUAL -->
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.02175" />
      </geometry>
	<material name="black">
		<color rgba="0.263 0.298 0.369 1"/>
	</material>
    </visual>
    <!-- FOOT COLLISION -->
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.02175" />
      </geometry>
      <material name="grey">
        <color rgba="0.7 0.7 0.7 0.5"/>
      </material>
    </collision>
   </link>


    <gazebo reference="wheel_r">
        <kp>1000000.0</kp>
        <kd>100.0</kd>
        <mu1>1.8</mu1>
        <mu2>1.8</mu2>
        <maxVel>1.0</maxVel>
        <maxContacts>1</maxContacts>
        <sensor name="foot_contact_sensor" type="contact">
                <always_on>true</always_on>
                <update_rate>1000.0</update_rate>
                <contact>
                <collision>wheel_r_collision</collision>
                </contact>
                <!-- the sensor readings in terms of force torques are expressed in the lowerleg frame
                because gazebo lumps the fake footframe with the real parent link, the normals are in the world frame-->
                <plugin name="foot_bumper" filename="libgazebo_ros_bumper.so">
                        <bumperTopicName>/$(arg robot_name)/foot_landing_r_bumper</bumperTopicName>
                        <!--robotNamespace>solo</robotNamespace-->
                        <frameName>wheel_r</frameName>
                </plugin>
        </sensor>
        <material>Gazebo/Black</material>
   </gazebo>
  


    <!--WHEEL JOINTS-->

        <joint name="wheel_joint_l" type="revolute">
            <parent link="foot_landing_l"/>
            <child link="wheel_l"/>
            <axis xyz="1 0 0"/>
            <origin xyz="-${WHEEL_pos} 0  0" rpy="0 -1.57 0" />         
            <limit effort="100" lower="-1e10" upper="1e10" velocity="100"/>
            <dynamics damping="0.0" friction="0.0"/>
        </joint>

        <!-- WHEEL ASSEMBLY -->
        <link name="wheel_l">
            <!--VISUAL-->
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                       <mesh filename="package://climbingrobot_description/meshes/wheel_y.stl"/>
                </geometry>
                       <material name="blue">
       			 <color rgba="0 0 1  1.0"/>
      		</material>
            </visual>

            <!--COLLISION-->
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                       <mesh filename="package://climbingrobot_description/meshes/wheel_y.stl"/>
                </geometry>
            </collision>

               <inertial>
                    <origin xyz="0 0 0" rpy="0 0 0"/>
                    <mass value="0.00693606"/>
                    <inertia ixx="0.00000057" ixy="0.0" ixz="0.0" iyy="0.00000084" iyz="0.0" izz="0.00000053"/>
                </inertial>
        </link>


        <joint name="wheel_joint_r" type="revolute">
            <parent link="foot_landing_r"/>
            <child link="wheel_r"/>
            <axis xyz="1 0 0"/>
            <origin xyz="-${WHEEL_pos} 0  0" rpy="0 -1.57 0" />         
            <limit effort="100" lower="-1e10" upper="1e10" velocity="100"/>
            <dynamics damping="0.0" friction="0.0"/>
        </joint>

        <!-- WHEEL ASSEMBLY -->
        <link name="wheel_r">
            <!--VISUAL-->
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                       <mesh filename="package://climbingrobot_description/meshes/wheel_y.stl"/>
                </geometry>
                  <material name="blue">
       			 <color rgba="0 0 1  1.0"/>
      		</material>
            </visual>

            <!--COLLISION-->
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                       <mesh filename="package://climbingrobot_description/meshes/wheel_y.stl"/>
                </geometry>
            </collision>

               <inertial>
                    <origin xyz="0 0 0" rpy="0 0 0"/>
                    <mass value="0.00693606"/>
                    <inertia ixx="0.00000057" ixy="0.0" ixz="0.0" iyy="0.00000084" iyz="0.0" izz="0.00000053"/>
                </inertial>
        </link>


  <!-- Joint between the base and the ${prefix} upper leg -->
  <joint name="hip_pitch" type="revolute">
    <parent link="base_link"/>
    <child link="upper_link1"/>
    <limit effort="1000" velocity="100.0" lower="-100" upper="100"/>
    <!-- joints rotates around the y-axis -->
    <axis xyz="0 -1 0"/>
    <origin rpy="0 0 0" xyz="0.0 -0.02 0.025"/>
    <!-- pybullet simulation parameters -->
    <dynamics damping="0.0" friction="0.0"/>
  </joint>
  <link name="upper_link1">
    <!-- Left upper leg inertia -->
    <inertial>
      <origin rpy="0 0 0" xyz="0.0000 0.0 -0.0"/>
      <mass value="0.5"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.00004671" izz="0.01"/>
    </inertial>
    <!-- UPPER LEG LINK VISUAL 
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://climbingrobot_description/meshes/obj/with_foot/solo_upper_leg_left_side.obj"/>
      </geometry>
      <material name="grey">
        <color rgba="0.8 0.8 0.8 1.0"/>
      </material>
    </visual>-->
    <!-- UPPER LEG LINK COLLISION 
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://climbingrobot_description/meshes/obj/with_foot/solo_upper_leg_left_side.obj"/>
      </geometry>
        <material name="white">
        	<color rgba="0.898 0.913 0.941 1.0"/>
    	</material>
    </collision>-->
    <!-- Bullet specific paramters -->
    <contact>
      <lateral_friction value="1.0"/>
      <restitution value="0.5"/>
    </contact>
  </link>

  <joint name="hip_roll" type="revolute">
    <parent link="upper_link1"/>
    <child link="upper_link2"/>
    <limit effort="1000" velocity="100.0" lower="-100" upper="100"/>
    <!-- joints rotates around the y-axis -->
    <axis xyz="-1 0 0"/>
    <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
    <!-- pybullet simulation parameters -->
    <dynamics damping="0.0" friction="0.0"/>
  </joint>
  <link name="upper_link2">
    <!-- Left upper leg inertia -->
    <inertial>
      <origin rpy="0 0 0" xyz="0.0000 0.0 -0.0"/>
      <mass value="0.5"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.00004671" izz="0.01"/>
    </inertial>
    <!-- UPPER LEG LINK VISUAL -->
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://climbingrobot_description/meshes/obj/with_foot/solo_upper_leg_left_side.obj"/>
      </geometry>
      <material name="grey">
        <color rgba="0.7 0.7 0.7 0.5"/>
      </material>
    </visual>
    <!-- UPPER LEG LINK COLLISION -->
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://climbingrobot_description/meshes/obj/with_foot/solo_upper_leg_left_side.obj"/>
      </geometry>
        <material name="white">
        	<color rgba="0.898 0.913 0.941 1.0"/>
    	</material>
    </collision>
    <!-- Bullet specific paramters -->
    <contact>
      <lateral_friction value="1.0"/>
      <restitution value="0.5"/>
    </contact>
  </link>
  <!-- END UPPER LEG LINK -->

  <!-- KFE: Joint between the upper leg and the lower leg -->
  <joint name="knee" type="prismatic">
    <parent link="upper_link2"/>
    <child link="lower_link"/>
    <limit effort="1000" velocity="100.0" lower="-100" upper="100"/>
    <!-- joints rotates around the y-axis -->
    <axis xyz="0 0 1"/>
    <origin rpy="0 0 0" xyz="0 0.02 -0.08"/>
    <!-- pybullet simulation parameters -->
    <dynamics damping="0.0" friction="0.0"/>
  </joint>
  <link name="lower_link">
    <!-- Left lower leg inertia -->
    <inertial>
      <origin rpy="0 0 0" xyz="0.0 0.0 -0.09"/>
      <mass value="0.5"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.00000305" izz="0.01"/>
    </inertial>
    <!-- LOWER LEG LINK VISUAL -->
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://climbingrobot_description/meshes/obj/with_foot/solo_lower_leg_left_side.obj" scale="1 1 1.5"/>
      </geometry>
        <material name="white">
        	<color rgba="0.898 0.913 0.941 1.0"/>
    	</material>
    </visual>
    <!-- LOWER LEG LINK COLLISION -->
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://climbingrobot_description/meshes/obj/with_foot/solo_lower_leg_left_side.obj"/>
      </geometry>
      <material name="grey">
        <color rgba="0.7 0.7 0.7 0.5"/>
      </material>
    </collision>
    <!-- Bullet specific paramters -->
    <contact>
      <lateral_friction value="1.0"/>
      <restitution value="0.5"/>
    </contact>
  </link>
  <!-- END LOWER LEG LINK -->
  <!-- KFE: Joint between the upper leg and the lower leg -->
  <joint name="ankle" type="fixed">
    <parent link="lower_link"/>
    <child link="foot"/>
    <origin rpy="0 0 0" xyz="0 0.008 -0.24"/>
    <!-- Limits (usefull?) -->
    <limit effort="1000" lower="-10" upper="10" velocity="1000"/>
    <!-- pybullet simulation parameters -->
    <dynamics damping="0.0" friction="0.0"/>
  </joint>
  <link name="foot">
    <!-- FOOT INERTIAL -->
    <!-- This link is symmetrical left or right -->
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0.00035767"/>
      <mass value="0.00693606"/>
      <inertia ixx="0.00000057" ixy="0.0" ixz="0.0" iyy="0.00000084" iyz="0.0" izz="0.00000053"/>
    </inertial>
    <!-- FOOT VISUAL -->
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.02175" />
      </geometry>
	<material name="black">
		<color rgba="0.263 0.298 0.369 1"/>
	</material>
    </visual>
    <!-- FOOT COLLISION -->
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.02175" />
      </geometry>
      <material name="grey">
        <color rgba="0.7 0.7 0.7 0.5"/>
      </material>
    </collision>

  </link>
  <!-- END LOWER LEG LINK -->
  <!-- Joint between the base and the ${prefix} upper leg -->


    <gazebo reference="foot">
        <kp>1000000.0</kp>
        <kd>100.0</kd>
        <mu1>1.8</mu1>
        <mu2>1.8</mu2>
        <maxVel>1.0</maxVel>
        <maxContacts>1</maxContacts>
        <sensor name="foot_contact_sensor" type="contact">
                <always_on>true</always_on>
                <update_rate>1000.0</update_rate>
                <contact>
                <collision>lower_link_fixed_joint_lump__foot_collision_1</collision>
                </contact>
                <!-- the sensor readings in terms of force torques are expressed in the lowerleg frame
                because gazebo lumps the fake footframe with the real parent link, the normals are in the world frame-->
                <plugin name="foot_bumper" filename="libgazebo_ros_bumper.so">
                        <bumperTopicName>/$(arg robot_name)/foot_bumper</bumperTopicName>
                        <!--robotNamespace>solo</robotNamespace-->
                        <frameName>foot</frameName>
                </plugin>
        </sensor>
        <material>Gazebo/Black</material>
   </gazebo>


   <xacro:climbingrobot_transmission/>

</robot>
