// Generated by gencpp from file ros_impedance_controller/ContactsState.msg
// DO NOT EDIT!


#ifndef ROS_IMPEDANCE_CONTROLLER_MESSAGE_CONTACTSSTATE_H
#define ROS_IMPEDANCE_CONTROLLER_MESSAGE_CONTACTSSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_impedance_controller
{
template <class ContainerAllocator>
struct ContactsState_
{
  typedef ContactsState_<ContainerAllocator> Type;

  ContactsState_()
    : FL(false)
    , FR(false)
    , HL(false)
    , HR(false)  {
    }
  ContactsState_(const ContainerAllocator& _alloc)
    : FL(false)
    , FR(false)
    , HL(false)
    , HR(false)  {
  (void)_alloc;
    }



   typedef uint8_t _FL_type;
  _FL_type FL;

   typedef uint8_t _FR_type;
  _FR_type FR;

   typedef uint8_t _HL_type;
  _HL_type HL;

   typedef uint8_t _HR_type;
  _HR_type HR;





  typedef boost::shared_ptr< ::ros_impedance_controller::ContactsState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_impedance_controller::ContactsState_<ContainerAllocator> const> ConstPtr;

}; // struct ContactsState_

typedef ::ros_impedance_controller::ContactsState_<std::allocator<void> > ContactsState;

typedef boost::shared_ptr< ::ros_impedance_controller::ContactsState > ContactsStatePtr;
typedef boost::shared_ptr< ::ros_impedance_controller::ContactsState const> ContactsStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_impedance_controller::ContactsState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_impedance_controller::ContactsState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_impedance_controller::ContactsState_<ContainerAllocator1> & lhs, const ::ros_impedance_controller::ContactsState_<ContainerAllocator2> & rhs)
{
  return lhs.FL == rhs.FL &&
    lhs.FR == rhs.FR &&
    lhs.HL == rhs.HL &&
    lhs.HR == rhs.HR;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_impedance_controller::ContactsState_<ContainerAllocator1> & lhs, const ::ros_impedance_controller::ContactsState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_impedance_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_impedance_controller::ContactsState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_impedance_controller::ContactsState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_impedance_controller::ContactsState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_impedance_controller::ContactsState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_impedance_controller::ContactsState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_impedance_controller::ContactsState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_impedance_controller::ContactsState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9c1b6206dc127b95cf027c31c258fa92";
  }

  static const char* value(const ::ros_impedance_controller::ContactsState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9c1b6206dc127b95ULL;
  static const uint64_t static_value2 = 0xcf027c31c258fa92ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_impedance_controller::ContactsState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_impedance_controller/ContactsState";
  }

  static const char* value(const ::ros_impedance_controller::ContactsState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_impedance_controller::ContactsState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool FL\n"
"bool FR\n"
"bool HL\n"
"bool HR\n"
;
  }

  static const char* value(const ::ros_impedance_controller::ContactsState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_impedance_controller::ContactsState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.FL);
      stream.next(m.FR);
      stream.next(m.HL);
      stream.next(m.HR);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ContactsState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_impedance_controller::ContactsState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_impedance_controller::ContactsState_<ContainerAllocator>& v)
  {
    s << indent << "FL: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.FL);
    s << indent << "FR: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.FR);
    s << indent << "HL: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.HL);
    s << indent << "HR: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.HR);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_IMPEDANCE_CONTROLLER_MESSAGE_CONTACTSSTATE_H
