// Generated by gencpp from file ros_impedance_controller/get_effort_pidRequest.msg
// DO NOT EDIT!


#ifndef ROS_IMPEDANCE_CONTROLLER_MESSAGE_GET_EFFORT_PIDREQUEST_H
#define ROS_IMPEDANCE_CONTROLLER_MESSAGE_GET_EFFORT_PIDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_impedance_controller
{
template <class ContainerAllocator>
struct get_effort_pidRequest_
{
  typedef get_effort_pidRequest_<ContainerAllocator> Type;

  get_effort_pidRequest_()
    : name()
    , effort_pid()  {
    }
  get_effort_pidRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , effort_pid(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _name_type;
  _name_type name;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _effort_pid_type;
  _effort_pid_type effort_pid;





  typedef boost::shared_ptr< ::ros_impedance_controller::get_effort_pidRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_impedance_controller::get_effort_pidRequest_<ContainerAllocator> const> ConstPtr;

}; // struct get_effort_pidRequest_

typedef ::ros_impedance_controller::get_effort_pidRequest_<std::allocator<void> > get_effort_pidRequest;

typedef boost::shared_ptr< ::ros_impedance_controller::get_effort_pidRequest > get_effort_pidRequestPtr;
typedef boost::shared_ptr< ::ros_impedance_controller::get_effort_pidRequest const> get_effort_pidRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_impedance_controller::get_effort_pidRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_impedance_controller::get_effort_pidRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_impedance_controller::get_effort_pidRequest_<ContainerAllocator1> & lhs, const ::ros_impedance_controller::get_effort_pidRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.effort_pid == rhs.effort_pid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_impedance_controller::get_effort_pidRequest_<ContainerAllocator1> & lhs, const ::ros_impedance_controller::get_effort_pidRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_impedance_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_impedance_controller::get_effort_pidRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_impedance_controller::get_effort_pidRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_impedance_controller::get_effort_pidRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_impedance_controller::get_effort_pidRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_impedance_controller::get_effort_pidRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_impedance_controller::get_effort_pidRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_impedance_controller::get_effort_pidRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cb4c22c1f92577e872da1b0bd5fe8258";
  }

  static const char* value(const ::ros_impedance_controller::get_effort_pidRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcb4c22c1f92577e8ULL;
  static const uint64_t static_value2 = 0x72da1b0bd5fe8258ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_impedance_controller::get_effort_pidRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_impedance_controller/get_effort_pidRequest";
  }

  static const char* value(const ::ros_impedance_controller::get_effort_pidRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_impedance_controller::get_effort_pidRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] name\n"
"float64[] effort_pid\n"
;
  }

  static const char* value(const ::ros_impedance_controller::get_effort_pidRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_impedance_controller::get_effort_pidRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.effort_pid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct get_effort_pidRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_impedance_controller::get_effort_pidRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_impedance_controller::get_effort_pidRequest_<ContainerAllocator>& v)
  {
    s << indent << "name[]" << std::endl;
    for (size_t i = 0; i < v.name.size(); ++i)
    {
      s << indent << "  name[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name[i]);
    }
    s << indent << "effort_pid[]" << std::endl;
    for (size_t i = 0; i < v.effort_pid.size(); ++i)
    {
      s << indent << "  effort_pid[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.effort_pid[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_IMPEDANCE_CONTROLLER_MESSAGE_GET_EFFORT_PIDREQUEST_H
