(cl:in-package motion-msg)
(cl:export '(COMMAND_ID-VAL
          COMMAND_ID
          SEND_ACK-VAL
          SEND_ACK
          REAL_ROBOT-VAL
          REAL_ROBOT
          W_TIME-VAL
          W_TIME
          COORD_X-VAL
          COORD_X
          COORD_Y-VAL
          COORD_Y
          COORD_Z-VAL
          COORD_Z
          ROT_ROLL-VAL
          ROT_ROLL
          ROT_PITCH-VAL
          ROT_PITCH
          ROT_YAW-VAL
          ROT_YAW
          GASP_DIAM-VAL
          GASP_DIAM
          DEST_X-VAL
          DEST_X
          DEST_Y-VAL
          DEST_Y
          DEST_Z-VAL
          DEST_Z
          DEST_ROLL-VAL
          DEST_ROLL
          DEST_PITCH-VAL
          DEST_PITCH
          DEST_YAW-VAL
          DEST_YAW
          UNGASP_DIAM-VAL
          UNGASP_DIAM
          AUTHKEY-VAL
          AUTHKEY
))